# Generated by Django 4.2.8 on 2025-11-24 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceReviewCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('submission_deadline', models.DateField()),
                ('self_assessment_link', models.URLField(blank=True)),
                ('guidelines', models.TextField(blank=True)),
                ('criteria', models.TextField(blank=True)),
                ('announcement_sent', models.BooleanField(default=False)),
                ('upcoming_notification_sent', models.BooleanField(default=False)),
                ('self_assessment_sent', models.BooleanField(default=False)),
                ('guidelines_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_cycles_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Performance Review Cycle',
                'verbose_name_plural': 'Performance Review Cycles',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Self-Assessment'), ('submitted', 'Self-Assessment Submitted'), ('review', 'Manager Review In Progress'), ('meeting', 'Meeting Scheduled'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('submission_deadline', models.DateField()),
                ('self_assessment_submitted', models.BooleanField(default=False)),
                ('self_assessment_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('manager_review_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('meeting_scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('meeting_confirmation_sent', models.BooleanField(default=False)),
                ('review_summary', models.TextField(blank=True)),
                ('summary_shared', models.BooleanField(default=False)),
                ('goals_next_period', models.TextField(blank=True)),
                ('goals_shared', models.BooleanField(default=False)),
                ('reminder_7_sent', models.BooleanField(default=False)),
                ('reminder_3_sent', models.BooleanField(default=False)),
                ('reminder_1_sent', models.BooleanField(default=False)),
                ('overdue_notice_sent', models.BooleanField(default=False)),
                ('last_quarterly_goal_reminder', models.DateTimeField(blank=True, null=True)),
                ('appreciation_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='performance.performancereviewcycle')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Performance Review',
                'verbose_name_plural': 'Performance Reviews',
                'ordering': ['employee__username'],
                'unique_together': {('cycle', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='PerformanceGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('on_track', 'On Track'), ('off_track', 'Off Track'), ('completed', 'Completed')], default='on_track', max_length=20)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('course_correction_note', models.TextField(blank=True)),
                ('achievement_notified', models.BooleanField(default=False)),
                ('course_correction_notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='performance.performancereview')),
            ],
            options={
                'verbose_name': 'Performance Goal',
                'verbose_name_plural': 'Performance Goals',
                'ordering': ['due_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('announcement', 'Review Period Announcement'), ('upcoming', 'Upcoming Review Notification'), ('self_assessment', 'Self-Assessment Link'), ('guidelines', 'Guidelines & Criteria'), ('reminder_7', '7 Day Reminder'), ('reminder_3', '3 Day Reminder'), ('reminder_1', '1 Day Reminder'), ('overdue', 'Overdue Notification'), ('meeting_confirmation', 'Meeting Confirmation'), ('review_summary', 'Review Summary'), ('goal_setting', 'Goal Setting'), ('appreciation', 'Appreciation Email'), ('goal_quarter', 'Quarterly Goal Reminder'), ('goal_achievement', 'Goal Achievement'), ('course_correction', 'Course Correction Suggestion')], max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('recipient_list', models.TextField()),
                ('status', models.CharField(default='sent', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='performance.performancereviewcycle')),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='performance.performancegoal')),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='performance.performancereview')),
            ],
            options={
                'verbose_name': 'Performance Email Log',
                'verbose_name_plural': 'Performance Email Logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='AppreciationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('cc_team', models.BooleanField(default=False)),
                ('cc_hr', models.BooleanField(default=True)),
                ('badge_attachment', models.FileField(blank=True, null=True, upload_to='badges/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appreciations_received', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appreciations_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appreciation Record',
                'verbose_name_plural': 'Appreciation Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
