# Generated by Django 5.2.8 on 2025-11-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="performancereview",
            name="self_assessment_content",
            field=models.TextField(
                blank=True, help_text="Employee's self-assessment submission"
            ),
        ),
    ]
