# Generated by Django 4.2.8 on 2025-11-21 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_working_day', models.DateField()),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('exit_email_sent', models.BooleanField(default=False)),
                ('farewell_email_sent', models.BooleanField(default=False)),
                ('final_settlement', models.TextField(blank=True, help_text='Final settlement details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offboarding', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Offboarding Records',
            },
        ),
        migrations.CreateModel(
            name='Onboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('paused', 'Paused')], default='in_progress', max_length=20)),
                ('welcome_email_sent', models.BooleanField(default=False)),
                ('day_3_checklist_sent', models.BooleanField(default=False)),
                ('day_5_checklist_sent', models.BooleanField(default=False)),
                ('day_7_checklist_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Onboarding Records',
            },
        ),
        migrations.CreateModel(
            name='OnboardingEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('email_type', models.CharField(choices=[('welcome', 'Welcome Email'), ('day_3', 'Day 3 Checklist'), ('day_5', 'Day 5 Checklist'), ('day_7', 'Day 7 Checklist'), ('exit_process', 'Exit Process'), ('farewell', 'Farewell Email')], max_length=50)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='sent', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Onboarding Email Logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('day', models.IntegerField(help_text='Day number (3, 5, 7, etc.)')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='onboarding.onboarding')),
            ],
            options={
                'verbose_name_plural': 'Onboarding Checklists',
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='OffboardingChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='onboarding.offboarding')),
            ],
            options={
                'verbose_name_plural': 'Offboarding Checklists',
                'ordering': ['created_at'],
            },
        ),
    ]
